apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kaptn-read-cluster
rules:
  # Core resources used in overviews
  - apiGroups: [""]
    resources: ["pods","nodes","namespaces","resourcequotas","services","endpoints","events"]
    verbs: ["get","list","watch"]
  # Workloads (if your UI lists them)
  - apiGroups: ["apps"]
    resources: ["deployments","daemonsets","statefulsets","replicasets"]
    verbs: ["get","list","watch"]
  # Metrics API
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods","nodes"]
    verbs: ["get","list","watch"]
  # Istio networking resources
  - apiGroups: ["networking.istio.io"]
    resources: ["virtualservices","gateways"]
    verbs: ["get","list","watch"]
  # CustomResourceDefinitions for capability detection
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kaptn-read-cluster-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kaptn-read-cluster
subjects:
  - kind: ServiceAccount
    name: kaptn-sa
    namespace: kaptn