apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: dummy-snapclass
driver: local-path
deletionPolicy: Delete
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: test-snapshot
  namespace: kaptn
spec:
  volumeSnapshotClassName: dummy-snapclass
  source:
    persistentVolumeClaimName: pvc-cecc5ccd-93b4-4694-a7a4-aef4a69a7b94