apiVersion: batch/v1
kind: Job
metadata:
  name: test-job-good
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: test-job-good
        image: busybox
        command: ["/bin/sh", "-c", "echo start; sleep 5; echo finish"]
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
      restartPolicy: Never
  backoffLimit: 4
