package routes

import (
	"net/http"

	"github.com/go-chi/chi/v5"
)

// MountRead mounts read-only routes (require read permissions)
func MountRead(r chi.Router, s interface{}) {
	// Type assert to access server methods and properties
	server := s.(interface {
		// All read handler methods (abbreviated for space - these match the original server methods)
		handleCheckPermission(w http.ResponseWriter, r *http.Request)
		handleGetActionPermissions(w http.ResponseWriter, r *http.Request)
		handleCheckPageAccess(w http.ResponseWriter, r *http.Request)
		handleGetUserNamespacePermissions(w http.ResponseWriter, r *http.Request)
		handleBulkPermissionCheck(w http.ResponseWriter, r *http.Request)
		handleAuthzCapabilities(w http.ResponseWriter, r *http.Request)
		handleAuthzCapabilitiesRegistry(w http.ResponseWriter, r *http.Request)
		handleAuthzCapabilitiesStats(w http.ResponseWriter, r *http.Request)
		handleGetCapabilities(w http.ResponseWriter, r *http.Request)
		handleSearch(w http.ResponseWriter, r *http.Request)
		handleSearchStats(w http.ResponseWriter, r *http.Request)
		handleRefreshSearchCache(w http.ResponseWriter, r *http.Request)
		handleGetClusterTimeSeries(w http.ResponseWriter, r *http.Request)
		handleTimeSeriesHealth(w http.ResponseWriter, r *http.Request)
		handleGetTimeSeriesCapabilities(w http.ResponseWriter, r *http.Request)
		handleGetTimeSeriesNodes(w http.ResponseWriter, r *http.Request)
		handleGetTimeSeriesNamespaces(w http.ResponseWriter, r *http.Request)
		handleGetTimeSeriesPods(w http.ResponseWriter, r *http.Request)
		handleGetNodesTimeSeries(w http.ResponseWriter, r *http.Request)
		handleGetNodeTimeSeries(w http.ResponseWriter, r *http.Request)
		handleGetPodsTimeSeries(w http.ResponseWriter, r *http.Request)
		handleGetPodTimeSeries(w http.ResponseWriter, r *http.Request)
		handleGetNamespacesTimeSeries(w http.ResponseWriter, r *http.Request)
		handleGetNamespaceTimeSeries(w http.ResponseWriter, r *http.Request)
		handleListNodes(w http.ResponseWriter, r *http.Request)
		handleGetNode(w http.ResponseWriter, r *http.Request)
		handleListPods(w http.ResponseWriter, r *http.Request)
		handleGetPod(w http.ResponseWriter, r *http.Request)
		handleListDeployments(w http.ResponseWriter, r *http.Request)
		handleGetDeployment(w http.ResponseWriter, r *http.Request)
		handleListStatefulSets(w http.ResponseWriter, r *http.Request)
		handleGetStatefulSet(w http.ResponseWriter, r *http.Request)
		handleListReplicaSets(w http.ResponseWriter, r *http.Request)
		handleGetReplicaSet(w http.ResponseWriter, r *http.Request)
		handleListDaemonSets(w http.ResponseWriter, r *http.Request)
		handleGetDaemonSet(w http.ResponseWriter, r *http.Request)
		handleListJobs(w http.ResponseWriter, r *http.Request)
		handleGetJob(w http.ResponseWriter, r *http.Request)
		handleListCronJobs(w http.ResponseWriter, r *http.Request)
		handleGetCronJob(w http.ResponseWriter, r *http.Request)
		handleGetOverview(w http.ResponseWriter, r *http.Request)
		handleListActionJobs(w http.ResponseWriter, r *http.Request)
		handleGetActionJob(w http.ResponseWriter, r *http.Request)
		handleGetMetrics(w http.ResponseWriter, r *http.Request)
		handleGetNamespaceMetrics(w http.ResponseWriter, r *http.Request)
		handleListNamespaces(w http.ResponseWriter, r *http.Request)
		handleGetNamespace(w http.ResponseWriter, r *http.Request)
		handleListServices(w http.ResponseWriter, r *http.Request)
		handleListServicesInNamespace(w http.ResponseWriter, r *http.Request)
		handleGetService(w http.ResponseWriter, r *http.Request)
		handleListEvents(w http.ResponseWriter, r *http.Request)
		handleListEventsInNamespace(w http.ResponseWriter, r *http.Request)
		handleGetEvent(w http.ResponseWriter, r *http.Request)
		handleListAllIngresses(w http.ResponseWriter, r *http.Request)
		handleListIngresses(w http.ResponseWriter, r *http.Request)
		handleGetIngress(w http.ResponseWriter, r *http.Request)
		handleListIngressClasses(w http.ResponseWriter, r *http.Request)
		handleGetIngressClass(w http.ResponseWriter, r *http.Request)
		handleListEndpoints(w http.ResponseWriter, r *http.Request)
		handleGetEndpoints(w http.ResponseWriter, r *http.Request)
		handleListEndpointSlices(w http.ResponseWriter, r *http.Request)
		handleGetEndpointSlice(w http.ResponseWriter, r *http.Request)
		handleListConfigMaps(w http.ResponseWriter, r *http.Request)
		handleGetConfigMap(w http.ResponseWriter, r *http.Request)
		handleListSecrets(w http.ResponseWriter, r *http.Request)
		handleListSecretTypes(w http.ResponseWriter, r *http.Request)
		handleGetSecret(w http.ResponseWriter, r *http.Request)
		handleGetSecretData(w http.ResponseWriter, r *http.Request)
		handleGetSecretUsageExamples(w http.ResponseWriter, r *http.Request)
		handleListNetworkPolicies(w http.ResponseWriter, r *http.Request)
		handleGetNetworkPolicy(w http.ResponseWriter, r *http.Request)
		handleListRoles(w http.ResponseWriter, r *http.Request)
		handleGetRole(w http.ResponseWriter, r *http.Request)
		handleListRoleBindings(w http.ResponseWriter, r *http.Request)
		handleGetRoleBinding(w http.ResponseWriter, r *http.Request)
		handleListClusterRoles(w http.ResponseWriter, r *http.Request)
		handleGetClusterRole(w http.ResponseWriter, r *http.Request)
		handleListClusterRoleBindings(w http.ResponseWriter, r *http.Request)
		handleGetClusterRoleBinding(w http.ResponseWriter, r *http.Request)
		handleListRBACIdentities(w http.ResponseWriter, r *http.Request)
		handleListPersistentVolumes(w http.ResponseWriter, r *http.Request)
		handleGetPersistentVolume(w http.ResponseWriter, r *http.Request)
		handleListPersistentVolumeClaims(w http.ResponseWriter, r *http.Request)
		handleGetPersistentVolumeClaim(w http.ResponseWriter, r *http.Request)
		handleListStorageClasses(w http.ResponseWriter, r *http.Request)
		handleGetStorageClass(w http.ResponseWriter, r *http.Request)
		handleListCSIDrivers(w http.ResponseWriter, r *http.Request)
		handleGetCSIDriver(w http.ResponseWriter, r *http.Request)
		handleListVolumeSnapshots(w http.ResponseWriter, r *http.Request)
		handleGetVolumeSnapshot(w http.ResponseWriter, r *http.Request)
		handleListVolumeSnapshotClasses(w http.ResponseWriter, r *http.Request)
		handleGetVolumeSnapshotClass(w http.ResponseWriter, r *http.Request)
		handleListResourceQuotas(w http.ResponseWriter, r *http.Request)
		handleGetResourceQuota(w http.ResponseWriter, r *http.Request)
		handleListAPIResources(w http.ResponseWriter, r *http.Request)
		handleGetAPIResource(w http.ResponseWriter, r *http.Request)
		handleListCustomResourceDefinitions(w http.ResponseWriter, r *http.Request)
		handleGetCustomResourceDefinition(w http.ResponseWriter, r *http.Request)
		handleExportResource(w http.ResponseWriter, r *http.Request)
		handleExportClusterScopedResource(w http.ResponseWriter, r *http.Request)
		handleGetPodLogs(w http.ResponseWriter, r *http.Request)
		handleGetVisitors(w http.ResponseWriter, r *http.Request)
		handleListVirtualServices(w http.ResponseWriter, r *http.Request)
		handleGetVirtualService(w http.ResponseWriter, r *http.Request)
		handleGetVirtualServiceYAML(w http.ResponseWriter, r *http.Request)
		handleListGateways(w http.ResponseWriter, r *http.Request)
		handleGetGateway(w http.ResponseWriter, r *http.Request)
		handleGetGatewayYAML(w http.ResponseWriter, r *http.Request)
		handleGetSummaryCards(w http.ResponseWriter, r *http.Request)
		handleGetResourceSummary(w http.ResponseWriter, r *http.Request)
		handleGetNamespacedResourceSummary(w http.ResponseWriter, r *http.Request)
		handleNodesWebSocket(w http.ResponseWriter, r *http.Request)
		handlePodsWebSocket(w http.ResponseWriter, r *http.Request)
		handleServicesWebSocket(w http.ResponseWriter, r *http.Request)
		handleDeploymentsWebSocket(w http.ResponseWriter, r *http.Request)
		handleSecretsWebSocket(w http.ResponseWriter, r *http.Request)
		handleOverviewWebSocket(w http.ResponseWriter, r *http.Request)
		handleJobWebSocket(w http.ResponseWriter, r *http.Request)
		handleLogsWebSocket(w http.ResponseWriter, r *http.Request)
		handleTimeSeriesLiveWebSocket(w http.ResponseWriter, r *http.Request)
		handleClusterTimeSeriesLiveWebSocket(w http.ResponseWriter, r *http.Request)
	})

	// Note: Auth middleware will be applied at the group level in the main server setup

	// Permission checking endpoints for UI gating (Phase 6)
	r.Get("/permissions/check", server.handleCheckPermission)
	r.Get("/permissions/actions", server.handleGetActionPermissions)
	r.Get("/permissions/actions/{namespace}", server.handleGetActionPermissions)
	r.Get("/permissions/page-access", server.handleCheckPageAccess)
	r.Get("/permissions/namespaces", server.handleGetUserNamespacePermissions)
	r.Post("/permissions/bulk", server.handleBulkPermissionCheck)

	// Permission checking endpoints for Phase 6 UI gating (duplicate - but keeping mechanical move)
	r.Post("/permissions/bulk-check", server.handleBulkPermissionCheck)

	// Authorization capability endpoints (Phase 1)
	r.Post("/authz/capabilities", server.handleAuthzCapabilities)
	r.Get("/authz/capabilities/registry", server.handleAuthzCapabilitiesRegistry)
	r.Get("/authz/capabilities/stats", server.handleAuthzCapabilitiesStats)

	// Capabilities endpoint
	r.Get("/capabilities", server.handleGetCapabilities)

	// Search endpoints
	r.Get("/search", server.handleSearch)
	r.Get("/search/stats", server.handleSearchStats)
	r.Post("/search/refresh", server.handleRefreshSearchCache)

	// TimeSeries endpoints
	r.Get("/timeseries/cluster", server.handleGetClusterTimeSeries)
	r.Get("/timeseries/health", server.handleTimeSeriesHealth)
	r.Get("/timeseries/capabilities", server.handleGetTimeSeriesCapabilities)

	// Entity discovery endpoints for timeseries
	r.Get("/timeseries/entities/nodes", server.handleGetTimeSeriesNodes)
	r.Get("/timeseries/entities/namespaces", server.handleGetTimeSeriesNamespaces)
	r.Get("/timeseries/entities/pods", server.handleGetTimeSeriesPods)

	// New entity-specific endpoints
	r.Get("/timeseries/nodes", server.handleGetNodesTimeSeries)
	r.Get("/timeseries/nodes/{nodeName}", server.handleGetNodeTimeSeries)
	r.Get("/timeseries/pods", server.handleGetPodsTimeSeries)
	r.Get("/timeseries/pods/{namespace}/{podName}", server.handleGetPodTimeSeries)
	r.Get("/timeseries/namespaces", server.handleGetNamespacesTimeSeries)
	r.Get("/timeseries/namespaces/{namespace}", server.handleGetNamespaceTimeSeries)

	r.Get("/nodes", server.handleListNodes)
	r.Get("/nodes/{name}", server.handleGetNode)

	// Pods endpoints with new permission middleware (PR 2 test)
	// Note: For mechanical move, we preserve the middleware structure in the main server
	r.Get("/pods", server.handleListPods)

	r.Get("/pods/{namespace}/{name}", server.handleGetPod)
	r.Get("/deployments", server.handleListDeployments)
	r.Get("/deployments/{namespace}/{name}", server.handleGetDeployment)
	r.Get("/statefulsets", server.handleListStatefulSets)
	r.Get("/statefulsets/{namespace}/{name}", server.handleGetStatefulSet)
	r.Get("/replicasets", server.handleListReplicaSets)
	r.Get("/replicasets/{namespace}/{name}", server.handleGetReplicaSet)
	r.Get("/daemonsets", server.handleListDaemonSets)
	r.Get("/daemonsets/{namespace}/{name}", server.handleGetDaemonSet)
	r.Get("/k8s-jobs", server.handleListJobs)
	r.Get("/k8s-jobs/{namespace}/{name}", server.handleGetJob)
	r.Get("/cronjobs", server.handleListCronJobs)
	r.Get("/cronjobs/{namespace}/{name}", server.handleGetCronJob)
	r.Get("/overview", server.handleGetOverview)
	r.Get("/jobs", server.handleListActionJobs)
	r.Get("/jobs/{jobId}", server.handleGetActionJob)

	r.Get("/metrics", server.handleGetMetrics)
	r.Get("/metrics/namespace/{namespace}", server.handleGetNamespaceMetrics)
	r.Get("/namespaces", server.handleListNamespaces)
	r.Get("/namespaces/{name}", server.handleGetNamespace)
	r.Get("/services", server.handleListServices)
	r.Get("/services/{namespace}", server.handleListServicesInNamespace)
	r.Get("/services/{namespace}/{name}", server.handleGetService)
	r.Get("/events", server.handleListEvents)
	r.Get("/events/{namespace}", server.handleListEventsInNamespace)
	r.Get("/events/{namespace}/{name}", server.handleGetEvent)
	r.Get("/ingresses", server.handleListAllIngresses)
	r.Get("/ingresses/{namespace}", server.handleListIngresses)
	r.Get("/ingresses/{namespace}/{name}", server.handleGetIngress)
	r.Get("/ingress-classes", server.handleListIngressClasses)
	r.Get("/ingress-classes/{name}", server.handleGetIngressClass)
	r.Get("/endpoints", server.handleListEndpoints)
	r.Get("/endpoints/{namespace}/{name}", server.handleGetEndpoints)
	r.Get("/endpoint-slices", server.handleListEndpointSlices)
	r.Get("/endpoint-slices/{namespace}/{name}", server.handleGetEndpointSlice)
	r.Get("/config-maps", server.handleListConfigMaps)
	r.Get("/config-maps/{namespace}/{name}", server.handleGetConfigMap)
	r.Get("/secrets", server.handleListSecrets)
	r.Get("/secrets/types", server.handleListSecretTypes)
	r.Get("/secrets/{namespace}/{name}", server.handleGetSecret)
	r.Get("/secrets/{namespace}/{name}/data/{key}", server.handleGetSecretData)
	r.Get("/secrets/{namespace}/{name}/usage", server.handleGetSecretUsageExamples)
	r.Get("/network-policies", server.handleListNetworkPolicies)
	r.Get("/network-policies/{namespace}/{name}", server.handleGetNetworkPolicy)
	r.Get("/roles", server.handleListRoles)
	r.Get("/roles/{namespace}/{name}", server.handleGetRole)
	r.Get("/role-bindings", server.handleListRoleBindings)
	r.Get("/role-bindings/{namespace}/{name}", server.handleGetRoleBinding)
	r.Get("/cluster-roles", server.handleListClusterRoles)
	r.Get("/cluster-roles/{name}", server.handleGetClusterRole)
	r.Get("/cluster-role-bindings", server.handleListClusterRoleBindings)
	r.Get("/cluster-role-bindings/{name}", server.handleGetClusterRoleBinding)
	r.Get("/identities", server.handleListRBACIdentities)
	r.Get("/persistent-volumes", server.handleListPersistentVolumes)
	r.Get("/persistent-volumes/{name}", server.handleGetPersistentVolume)
	r.Get("/persistent-volume-claims", server.handleListPersistentVolumeClaims)
	r.Get("/persistent-volume-claims/{namespace}/{name}", server.handleGetPersistentVolumeClaim)
	r.Get("/storage-classes", server.handleListStorageClasses)
	r.Get("/storage-classes/{name}", server.handleGetStorageClass)
	r.Get("/csi-drivers", server.handleListCSIDrivers)
	r.Get("/csi-drivers/{name}", server.handleGetCSIDriver)
	r.Get("/volume-snapshots", server.handleListVolumeSnapshots)
	r.Get("/volume-snapshots/{namespace}/{name}", server.handleGetVolumeSnapshot)
	r.Get("/volume-snapshot-classes", server.handleListVolumeSnapshotClasses)
	r.Get("/volume-snapshot-classes/{name}", server.handleGetVolumeSnapshotClass)
	r.Get("/resource-quotas", server.handleListResourceQuotas)
	r.Get("/resource-quotas/{namespace}/{name}", server.handleGetResourceQuota)
	r.Get("/api-resources", server.handleListAPIResources)
	r.Get("/api-resources/{name}", server.handleGetAPIResource)
	r.Get("/crds", server.handleListCustomResourceDefinitions)
	r.Get("/crds/{name}", server.handleGetCustomResourceDefinition)
	r.Get("/export/{namespace}/{kind}/{name}", server.handleExportResource)
	r.Get("/export/{kind}/{name}", server.handleExportClusterScopedResource)
	r.Get("/pods/{namespace}/{podName}/logs", server.handleGetPodLogs)

	// Analytics endpoints
	r.Get("/analytics/visitors", server.handleGetVisitors)

	// Istio endpoints
	r.Get("/istio/virtualservices", server.handleListVirtualServices)
	r.Get("/istio/virtualservices/{namespace}/{name}", server.handleGetVirtualService)
	r.Get("/istio/virtualservices/{namespace}/{name}/yaml", server.handleGetVirtualServiceYAML)
	r.Get("/istio/gateways", server.handleListGateways)
	r.Get("/istio/gateways/{namespace}/{name}", server.handleGetGateway)
	r.Get("/istio/gateways/{namespace}/{name}/yaml", server.handleGetGatewayYAML)

	// Summary endpoints
	r.Get("/summaries/cards", server.handleGetSummaryCards)
	r.Get("/summaries/{resource}", server.handleGetResourceSummary)
	r.Get("/summaries/{resource}/namespaces/{namespace}", server.handleGetNamespacedResourceSummary)

	// WebSocket endpoints (require authentication for real-time data)
	r.Get("/stream/nodes", server.handleNodesWebSocket)
	r.Get("/stream/pods", server.handlePodsWebSocket)
	r.Get("/stream/services", server.handleServicesWebSocket)
	r.Get("/stream/deployments", server.handleDeploymentsWebSocket)
	r.Get("/stream/secrets", server.handleSecretsWebSocket)
	r.Get("/stream/overview", server.handleOverviewWebSocket)
	r.Get("/stream/jobs/{jobId}", server.handleJobWebSocket)
	r.Get("/stream/logs/{streamId}", server.handleLogsWebSocket)

	// TimeSeries WebSocket endpoints
	r.Get("/timeseries/live", server.handleTimeSeriesLiveWebSocket)
	r.Get("/timeseries/cluster/live", server.handleClusterTimeSeriesLiveWebSocket)
}
