name: Build and Deploy to Local Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: development
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Debug Image
        run: make push-debug

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Restart Kaptn Deployment
        run: |
          kubectl rollout restart deployment/kaptn -n monitoring
          kubectl rollout status deployment/kaptn -n monitoring

      - name: Deployment Summary
        run: |
          echo "## Kaptn Deployment" >> $GITHUB_STEP_SUMMARY
          echo "* **Image:** aaronlmathis/kaptn:debug" >> $GITHUB_STEP_SUMMARY
          echo "* **Namespace:** monitoring" >> $GITHUB_STEP_SUMMARY
          echo "* **Status:** Deployment triggered" >> $GITHUB_STEP_SUMMARY           